name = "Meowtys S3"
author = "Hilha"
version = "5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b6175e155539a2ac03c6b3279bde61a8060ed375772c0b910f9ddbb39b36b81"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
