name = "Meowtys S3"
author = "Hilha"
version = "5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8d34262feffb5ad6a42da0c80670d33783aead91bfdb7573a83250a0df0be07"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
