name = "Meowtys S3"
author = "Hilha"
version = "5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "84d464e46c2c80e93dcf2af4ab143be9425decf2e8baa05e51dfcf7c2721bfa7"

[versions]
forge = "40.3.11"
minecraft = "1.18.2"
